// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package dynamicform.actions;

import java.math.BigDecimal;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;

public class Calculate_Formula extends CustomJavaAction<java.math.BigDecimal>
{
	private java.lang.String Expression;
	private java.util.List<IMendixObject> __NumberList;
	private java.util.List<dynamicform.proxies.Number> NumberList;

	public Calculate_Formula(IContext context, java.lang.String Expression, java.util.List<IMendixObject> NumberList)
	{
		super(context);
		this.Expression = Expression;
		this.__NumberList = NumberList;
	}

	@java.lang.Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		this.NumberList = java.util.Optional.ofNullable(this.__NumberList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(__NumberListElement -> dynamicform.proxies.Number.initialize(getContext(), __NumberListElement))
			.collect(java.util.stream.Collectors.toList());

		// BEGIN USER CODE
		int value[] = new int[26];
		for(int i=0; i< NumberList.size();i++)
		{
			value[i] =NumberList.get(i).getNumberValue(this.getContext());
		}
		
		Expression e = new ExpressionBuilder(Expression)
				.variables("a", "b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z")
		        .build()
		        .setVariable("a", value[0])
		        .setVariable("b", value[1])
		        .setVariable("c", value[2])
		        .setVariable("d", value[3])
		        .setVariable("e", value[4])
		        .setVariable("f", value[5])
		        .setVariable("g", value[6])
		        .setVariable("h", value[7])
		        .setVariable("i", value[8])
		        .setVariable("j", value[9])
		        .setVariable("k", value[10])
		        .setVariable("l", value[11])
		        .setVariable("m", value[12])
		        .setVariable("n", value[13])
		        .setVariable("o", value[14])
		        .setVariable("p", value[15])
		        .setVariable("q", value[16])
		        .setVariable("r", value[17])
		        .setVariable("s", value[18])
		        .setVariable("t", value[19])
		        .setVariable("u", value[20])
		        .setVariable("v", value[21])
		        .setVariable("w", value[22])
		        .setVariable("x", value[23])
		        .setVariable("y", value[24])
		        .setVariable("z", value[25])
		        ;
		BigDecimal _a = new BigDecimal(0);
		try {
			BigDecimal x = new BigDecimal(e.evaluate());
		  _a = x;
		
		}catch(ArithmeticException a) {
			BigDecimal _b = new BigDecimal(0);
			return _b;
		}
		return _a;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Calculate_Formula";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
